# Inherits from default config
# https://github.com/brigade/scss-lint/blob/master/config/default.yml

scss_files: '*.scss'

linters:
  Indentation:
    character: tab
    width: 1

  LeadingZero:
    style: include_zero

  BorderZero:
    convention: none

  PropertySortOrder:
    order: smacss

  # Disabled

  SelectorFormat:
    enabled: false

  SelectorDepth:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  QualifyingElement:
    enabled: false

  UrlQuotes:
    enabled: false

  UnnecessaryParentReference:
    enabled: false
