language: node_js
node_js: stable
before_script: gem install scss_lint
script: npm test
branches:
  only:
    - master
deploy:
  provider: script
  script: node deploy.js
  skip_cleanup: true
  on:
    branch: master
